/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package marketflow.project;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Locale;

/**
 *
 * @author Pichau
 */
public class CadastrodeProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadastrodeProduto
     */
    public CadastrodeProduto() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnEscolhas = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        JPAviso = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JPPesquisa = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        TFIdProd = new javax.swing.JTextField();
        TFDescricao1 = new javax.swing.JTextField();
        JLDescricao1 = new javax.swing.JLabel();
        TFNome1 = new javax.swing.JTextField();
        JLNome1 = new javax.swing.JLabel();
        JLValor1 = new javax.swing.JLabel();
        TFValor1 = new javax.swing.JTextField();
        JLCategoria1 = new javax.swing.JLabel();
        TFCategoria1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        BtnBuscaProd = new javax.swing.JButton();
        JLErroinf = new javax.swing.JLabel();
        JLAlt = new javax.swing.JLabel();
        JPMenu = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JPCriar = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        JLDescricao = new javax.swing.JLabel();
        JLNome = new javax.swing.JLabel();
        TFNome = new javax.swing.JTextField();
        TFDescricao = new javax.swing.JTextField();
        JLValor = new javax.swing.JLabel();
        JLCategoria = new javax.swing.JLabel();
        TFCategoria = new javax.swing.JTextField();
        TFValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAResp = new javax.swing.JTextArea();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPAviso.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Escolha uma das opções.");

        javax.swing.GroupLayout JPAvisoLayout = new javax.swing.GroupLayout(JPAviso);
        JPAviso.setLayout(JPAvisoLayout);
        JPAvisoLayout.setHorizontalGroup(
            JPAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPAvisoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPAvisoLayout.setVerticalGroup(
            JPAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPAvisoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(JPAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, 1000, 530));

        JPPesquisa.setBackground(new java.awt.Color(255, 255, 255));
        JPPesquisa.setVisible(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Digite o ID do produto");
        jLabel4.setToolTipText("");

        TFIdProd.setBackground(new java.awt.Color(255, 255, 255));
        TFIdProd.setForeground(new java.awt.Color(0, 0, 0));
        TFIdProd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFIdProd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TFIdProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFIdProdActionPerformed(evt);
            }
        });

        TFDescricao1.setBackground(new java.awt.Color(255, 255, 255));
        TFDescricao1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFDescricao1.setForeground(new java.awt.Color(0, 0, 0));
        TFDescricao1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JLDescricao1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLDescricao1.setForeground(new java.awt.Color(0, 0, 0));
        JLDescricao1.setText("Descrição:");

        TFNome1.setBackground(new java.awt.Color(255, 255, 255));
        TFNome1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFNome1.setForeground(new java.awt.Color(0, 0, 0));
        TFNome1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TFNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNome1ActionPerformed(evt);
            }
        });

        JLNome1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLNome1.setForeground(new java.awt.Color(0, 0, 0));
        JLNome1.setText("Nome:");

        JLValor1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLValor1.setForeground(new java.awt.Color(0, 0, 0));
        JLValor1.setText("Valor:");

        TFValor1.setBackground(new java.awt.Color(255, 255, 255));
        TFValor1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFValor1.setForeground(new java.awt.Color(0, 0, 0));
        TFValor1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JLCategoria1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLCategoria1.setForeground(new java.awt.Color(0, 0, 0));
        JLCategoria1.setText("Categoria:");

        TFCategoria1.setBackground(new java.awt.Color(255, 255, 255));
        TFCategoria1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFCategoria1.setForeground(new java.awt.Color(0, 0, 0));
        TFCategoria1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton3.setBackground(new java.awt.Color(153, 204, 0));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Alterar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(153, 0, 51));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Excluir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        BtnBuscaProd.setBackground(new java.awt.Color(153, 255, 0));
        BtnBuscaProd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnBuscaProd.setForeground(new java.awt.Color(0, 0, 0));
        BtnBuscaProd.setText("Buscar");
        BtnBuscaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscaProdActionPerformed(evt);
            }
        });

        JLErroinf.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        JLErroinf.setForeground(new java.awt.Color(204, 0, 0));
        JLErroinf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLErroinf.setText("Digite o ID(codigo) do produto.");
        JLErroinf.setVisible(false);

        JLAlt.setVisible(false);
        JLAlt.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        JLAlt.setForeground(new java.awt.Color(204, 0, 0));
        JLAlt.setText("Alterado Com Sucesso!");

        javax.swing.GroupLayout JPPesquisaLayout = new javax.swing.GroupLayout(JPPesquisa);
        JPPesquisa.setLayout(JPPesquisaLayout);
        JPPesquisaLayout.setHorizontalGroup(
            JPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPPesquisaLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(JPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPPesquisaLayout.createSequentialGroup()
                        .addComponent(JLNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(267, 267, 267)
                        .addComponent(JLValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPPesquisaLayout.createSequentialGroup()
                        .addGroup(JPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JLDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFDescricao1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                            .addComponent(TFNome1))
                        .addGroup(JPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPPesquisaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addGroup(JPPesquisaLayout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addGroup(JPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 171, Short.MAX_VALUE))))))
            .addGroup(JPPesquisaLayout.createSequentialGroup()
                .addGroup(JPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPPesquisaLayout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(TFIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBuscaProd))
                    .addGroup(JPPesquisaLayout.createSequentialGroup()
                        .addGap(415, 415, 415)
                        .addComponent(JLErroinf))
                    .addGroup(JPPesquisaLayout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(JLAlt)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JPPesquisaLayout.setVerticalGroup(
            JPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLAlt)
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFIdProd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JLErroinf)
                .addGap(20, 20, 20)
                .addGroup(JPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(JPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLCategoria1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPPesquisaLayout.createSequentialGroup()
                        .addComponent(TFDescricao1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(JPPesquisaLayout.createSequentialGroup()
                        .addComponent(TFCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(JPPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))))
        );

        getContentPane().add(JPPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, 1000, 530));

        JPMenu.setBackground(new java.awt.Color(255, 255, 255));

        jToggleButton1.setBackground(new java.awt.Color(51, 102, 255));
        BtnEscolhas.add(jToggleButton1);
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton1.setText("Criar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setBackground(new java.awt.Color(0, 102, 255));
        BtnEscolhas.add(jToggleButton2);
        jToggleButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton2.setText("Pesquisar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("MarketFlow");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cadastro de Produto");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("< Voltar");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JPMenuLayout = new javax.swing.GroupLayout(JPMenu);
        JPMenu.setLayout(JPMenuLayout);
        JPMenuLayout.setHorizontalGroup(
            JPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPMenuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(276, 276, 276)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        JPMenuLayout.setVerticalGroup(
            JPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPMenuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1))
            .addGroup(JPMenuLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2))
            .addGroup(JPMenuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(JPMenuLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(JPMenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5))
        );

        getContentPane().add(JPMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 90));

        JPCriar.setBackground(new java.awt.Color(255, 255, 255));
        JPCriar.setVisible(false);

        jButton1.setBackground(new java.awt.Color(204, 204, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        JLDescricao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLDescricao.setForeground(new java.awt.Color(0, 0, 0));
        JLDescricao.setText("Descrição:");

        JLNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLNome.setForeground(new java.awt.Color(0, 0, 0));
        JLNome.setText("Nome:");

        TFNome.setBackground(new java.awt.Color(255, 255, 255));
        TFNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFNome.setForeground(new java.awt.Color(0, 0, 0));
        TFNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TFDescricao.setBackground(new java.awt.Color(255, 255, 255));
        TFDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFDescricao.setForeground(new java.awt.Color(0, 0, 0));
        TFDescricao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JLValor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLValor.setForeground(new java.awt.Color(0, 0, 0));
        JLValor.setText("Valor:");

        JLCategoria.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLCategoria.setForeground(new java.awt.Color(0, 0, 0));
        JLCategoria.setText("Categoria:");

        TFCategoria.setBackground(new java.awt.Color(255, 255, 255));
        TFCategoria.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFCategoria.setForeground(new java.awt.Color(0, 0, 0));
        TFCategoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TFValor.setBackground(new java.awt.Color(255, 255, 255));
        TFValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TFValor.setForeground(new java.awt.Color(0, 0, 0));
        TFValor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane1.setEnabled(false);

        TAResp.setBackground(new java.awt.Color(51, 51, 51));
        TAResp.setColumns(20);
        TAResp.setRows(5);
        jScrollPane1.setViewportView(TAResp);

        javax.swing.GroupLayout JPCriarLayout = new javax.swing.GroupLayout(JPCriar);
        JPCriar.setLayout(JPCriarLayout);
        JPCriarLayout.setHorizontalGroup(
            JPCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPCriarLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(JPCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLNome, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TFDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                        .addComponent(JLDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TFNome)))
                .addGap(134, 134, 134)
                .addGroup(JPCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JLValor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JLCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TFValor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TFCategoria)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPCriarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        JPCriarLayout.setVerticalGroup(
            JPCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPCriarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(JPCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLNome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLValor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFNome, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFValor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPCriarLayout.createSequentialGroup()
                        .addComponent(TFDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(JPCriarLayout.createSequentialGroup()
                        .addComponent(TFCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(JPCriarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        getContentPane().add(JPCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 89, 1000, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        JPCriar.setVisible(false);
        JPAviso.setVisible(false);
        JPPesquisa.setVisible(true);
        JLAlt.setVisible(false);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        JPCriar.setVisible(true);
        JPAviso.setVisible(false);
        JPPesquisa.setVisible(false);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void TFIdProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFIdProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFIdProdActionPerformed

    private void TFNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNome1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nome = TFNome.getText();
        String Descricao = TFDescricao.getText();
        double valor = Double.parseDouble(TFValor.getText());
        String Categoria = TFCategoria.getText();

        String Salvar = "INSERT INTO PRODUTOS (NOME, DESCRICAO, PRECO, CATEGORIA) VALUES (?, ?, ?, ?)";
        try {
            Connection conn = (Connection) DataBase.getConnection("MarketFlow", "root", "Gustavo@0314");
            PreparedStatement statement = conn.prepareStatement(Salvar);
            statement.setString(1, nome);
            statement.setString(2, Descricao);
            statement.setDouble(3, valor);
            statement.setString(4, Categoria);
            statement.executeUpdate();
            statement.close();
            System.out.println("Enviado Com Sucesso");
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("Erro!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    //Botão Limpar
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TFCategoria.setText("");
        TFDescricao.setText("");
        TFNome.setText("");
        TFValor.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Index ind = new Index();
        ind.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Index ind = new Index();
        ind.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    //Botão de pesquisa
    private void BtnBuscaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscaProdActionPerformed
        //Reset Erros
        JLErroinf.setVisible(false);
        //Variavel do ID
        int IDprodBusca = Integer.getInteger(TFIdProd.getText());

        String Pesquisa = String.format("SELECT * FROM PRODUTOS WHERE ID_PRODUTO = %d", IDprodBusca);

        //Inicio
        if ("".equals(TFIdProd.getText())) {
            JLErroinf.setVisible(true);
        }

            //Falta buscar ID
    }//GEN-LAST:event_BtnBuscaProdActionPerformed

    //Botão de Excluir
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        TFCategoria1.setText("");
        TFDescricao1.setText("");
        TFNome1.setText("");
        TFValor1.setText("");

        int IDprodExcluir = Integer.parseInt(TFIdProd.getText());

        String Delete = String.format("DELETE FROM PRODUTOS WHERE ID_PRODUTO = %d", IDprodExcluir);
        try {
            Connection conn = (Connection) DataBase.getConnection("MarketFlow", "root", "Gustavo@0314");
            DataBase.insert(conn, Delete);
            System.out.println("Enviado Com Sucesso");
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("Erro!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    //Botão de Alterar
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int IDprodAltera = Integer.parseInt(TFIdProd.getText());
        String nome = TFNome1.getText();
        String descricao = TFDescricao1.getText();
        double valor = Double.parseDouble(TFValor1.getText());
        String categoria = TFCategoria1.getText();

        String Update = String.format(Locale.US, "UPDATE PRODUTOS SET NOME = '%s', DESCRICAO = '%s', PRECO = %.2f, CATEGORIA = '%s' WHERE ID_PRODUTO = %d", nome, descricao, valor, categoria, IDprodAltera);
        try {
            Connection conn = (Connection) DataBase.getConnection("MarketFlow", "root", "Gustavo@0314");
            DataBase.insert(conn, Update);
            JLAlt.setVisible(true);
            System.out.println("Enviado Com Sucesso");
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("Erro!");
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        System.out.println("--- Conectando Java e MySQL ---");

        try {
            Connection conn = (Connection) DataBase.getConnection("MarketFlow", "root", "Gustavo@0314");

            System.out.println("Conexão com sucesso");
        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("Erro ao conectar!");
        }

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrodeProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrodeProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrodeProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrodeProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrodeProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscaProd;
    private javax.swing.ButtonGroup BtnEscolhas;
    private javax.swing.JLabel JLAlt;
    private javax.swing.JLabel JLCategoria;
    private javax.swing.JLabel JLCategoria1;
    private javax.swing.JLabel JLDescricao;
    private javax.swing.JLabel JLDescricao1;
    private javax.swing.JLabel JLErroinf;
    private javax.swing.JLabel JLNome;
    private javax.swing.JLabel JLNome1;
    private javax.swing.JLabel JLValor;
    private javax.swing.JLabel JLValor1;
    private javax.swing.JPanel JPAviso;
    private javax.swing.JPanel JPCriar;
    private javax.swing.JPanel JPMenu;
    private javax.swing.JPanel JPPesquisa;
    private javax.swing.JTextArea TAResp;
    private javax.swing.JTextField TFCategoria;
    private javax.swing.JTextField TFCategoria1;
    private javax.swing.JTextField TFDescricao;
    private javax.swing.JTextField TFDescricao1;
    private javax.swing.JTextField TFIdProd;
    private javax.swing.JTextField TFNome;
    private javax.swing.JTextField TFNome1;
    private javax.swing.JTextField TFValor;
    private javax.swing.JTextField TFValor1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
