/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package marketflow.project;

import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        JLErroInf.setVisible(false);
        JLErro4001.setVisible(false);
        JPCadastre.setVisible(false);
        JLInfCad.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPLogin = new javax.swing.JPanel();
        TFSenhaL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TFLoginL = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BtnLogin = new javax.swing.JButton();
        JLErro4001 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JLInfCad = new javax.swing.JLabel();
        JPCadastre = new javax.swing.JPanel();
        TFnomeC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TFCpfC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JLEmail = new javax.swing.JLabel();
        TFEmailC = new javax.swing.JTextField();
        JLSenha1 = new javax.swing.JLabel();
        TFSenhaC = new javax.swing.JTextField();
        BtnCadastrar = new javax.swing.JButton();
        JLErroInf = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPMenu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPLogin.setBackground(new java.awt.Color(255, 255, 255));

        TFSenhaL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFSenhaLActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Email:");

        TFLoginL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFLoginLActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Senha:");

        BtnLogin.setBackground(new java.awt.Color(204, 204, 0));
        BtnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnLogin.setForeground(new java.awt.Color(0, 0, 0));
        BtnLogin.setText("Entrar");
        BtnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BtnLoginMouseReleased(evt);
            }
        });
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });

        JLErro4001.setBackground(new java.awt.Color(0, 0, 0));
        JLErro4001.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLErro4001.setForeground(new java.awt.Color(204, 0, 0));
        JLErro4001.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLErro4001.setText("Erro 4001 - Insira todas as informações abaixo.");
        JLErro4001.setToolTipText("");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Novo na MarketFlow?");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 255));
        jLabel8.setText("Cadastrar");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        JLInfCad.setBackground(new java.awt.Color(153, 255, 0));
        JLInfCad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLInfCad.setForeground(new java.awt.Color(0, 0, 0));
        JLInfCad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLInfCad.setText("Cadastrado com Sucesso! Faça o Login.");
        JLInfCad.setOpaque(true);

        javax.swing.GroupLayout JPLoginLayout = new javax.swing.GroupLayout(JPLogin);
        JPLogin.setLayout(JPLoginLayout);
        JPLoginLayout.setHorizontalGroup(
            JPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLErro4001, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPLoginLayout.createSequentialGroup()
                .addGroup(JPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPLoginLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(JPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFLoginL, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFSenhaL, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(JPLoginLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPLoginLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(BtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
            .addComponent(JLInfCad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JPLoginLayout.setVerticalGroup(
            JPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPLoginLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(JLInfCad, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLErro4001, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TFLoginL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(TFSenhaL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(24, 24, 24)
                .addComponent(BtnLogin)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        getContentPane().add(JPLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 116, 450, 430));

        JPCadastre.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nome:");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Telefone");

        JLEmail.setForeground(new java.awt.Color(0, 0, 0));
        JLEmail.setText("E-mail");

        JLSenha1.setForeground(new java.awt.Color(0, 0, 0));
        JLSenha1.setText("Senha:");

        BtnCadastrar.setBackground(new java.awt.Color(204, 204, 0));
        BtnCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        BtnCadastrar.setText("Cadastrar");
        BtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCadastrarActionPerformed(evt);
            }
        });

        JLErroInf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JLErroInf.setForeground(new java.awt.Color(153, 0, 0));
        JLErroInf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLErroInf.setText("Erro 4001 - Insira todas as informações abaixo.");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Tem uma Conta?");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 255));
        jLabel9.setText("Entre");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JPCadastreLayout = new javax.swing.GroupLayout(JPCadastre);
        JPCadastre.setLayout(JPCadastreLayout);
        JPCadastreLayout.setHorizontalGroup(
            JPCadastreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLErroInf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(JPCadastreLayout.createSequentialGroup()
                .addGroup(JPCadastreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPCadastreLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(JPCadastreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFSenhaC, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFEmailC, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFCpfC, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TFnomeC, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPCadastreLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JLSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPCadastreLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(BtnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        JPCadastreLayout.setVerticalGroup(
            JPCadastreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPCadastreLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(JLErroInf, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFnomeC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(TFCpfC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFEmailC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JLSenha1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFSenhaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(JPCadastreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(BtnCadastrar)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        getContentPane().add(JPCadastre, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 116, 450, 430));

        jPMenu.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Swis721 Blk BT", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cadastre-se");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setFont(new java.awt.Font("Swis721 Blk BT", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MarketFlow");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("< Voltar");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPMenuLayout = new javax.swing.GroupLayout(jPMenu);
        jPMenu.setLayout(jPMenuLayout);
        jPMenuLayout.setHorizontalGroup(
            jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuLayout.createSequentialGroup()
                .addGroup(jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPMenuLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPMenuLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel10)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPMenuLayout.setVerticalGroup(
            jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 119));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Menu Botão Cadastrar
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JPLogin.setVisible(false);
        JPCadastre.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    //Menu Botão Login
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JPLogin.setVisible(true);
        JPCadastre.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed


    private void TFSenhaLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFSenhaLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFSenhaLActionPerformed

    //TF de Email Login
    private void TFLoginLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFLoginLActionPerformed

    }//GEN-LAST:event_TFLoginLActionPerformed

    //Botão Cadastrar
    private void BtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCadastrarActionPerformed
        //Reset das informações
        JLErroInf.setVisible(false);
        JLInfCad.setVisible(false);

        //verificação de conteudo no TF(TextField)
        if ("".equals(TFCpfC.getText()) || "".equals(TFEmailC.getText()) || "".equals(TFSenhaC.getText()) || "".equals(TFnomeC.getText())) {
            JLErroInf.setVisible(true);
        } else {
            String nome = TFnomeC.getText();
            String Telefone = TFCpfC.getText();
            String email = TFEmailC.getText();
            String senha = TFSenhaC.getText();
            String Cadastro = "INSERT INTO CLIENTES (NOME, TELEFONE, EMAIL, SENHA) VALUES (?, ?, ?, ?)";

            try {
                Connection conn = (Connection) DataBase.getConnection("MarketFlow", "root", "Gustavo@0314");
                PreparedStatement statement = conn.prepareStatement(Cadastro);
                statement.setString(1, nome);
                statement.setString(2, Telefone);
                statement.setString(3, email);
                statement.setString(4, senha);
                statement.executeUpdate();
                statement.close();
                System.out.println("Enviado Com Sucesso");
            } catch (ClassNotFoundException | SQLException e) {
                System.out.println("Erro!");
            }

            JPCadastre.setVisible(false);
            JPLogin.setVisible(true);
            JLInfCad.setVisible(true);
        }

    }//GEN-LAST:event_BtnCadastrarActionPerformed

    //Botão Login
    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        //Reset das informações
        JLErro4001.setVisible(false);

        //verificação de conteudo no TF(TextField)
        if ("".equals(TFLoginL.getText()) || "".equals(TFSenhaL.getText())) {
            JLErro4001.setVisible(true);
        } else {
            String login = TFLoginL.getText();
            String senha = TFSenhaL.getText();

            String query = String.format("SELECT * FROM CLIENTES WHERE EMAIL = '%s' AND SENHA = '%s'", login, senha);
            try {
                Connection conn = DataBase.getConnection("MarketFlow", "root", "Gustavo@0314");

                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery(query);

                if (rs.next()) {
                    System.out.println("Enviado Com Sucesso");
                    Index ind = new Index();
                    ind.setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Usuário não cadastrado");
                }

                rs.close();
                stmt.close();
                conn.close();
            } catch (ClassNotFoundException | SQLException e) {
                System.out.println("Erro: " + e.getMessage());
            }

        }
    }//GEN-LAST:event_BtnLoginActionPerformed

    private void BtnLoginMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnLoginMouseReleased

    }//GEN-LAST:event_BtnLoginMouseReleased

    //TEXTO da Pergunta de Cadastro
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        JPLogin.setVisible(false);
        JPCadastre.setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    //TEXTO da Pergunta de Entre
    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        JPLogin.setVisible(true);
        JPCadastre.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        Index ind = new Index();
        ind.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCadastrar;
    private javax.swing.JButton BtnLogin;
    private javax.swing.JLabel JLEmail;
    private javax.swing.JLabel JLErro4001;
    private javax.swing.JLabel JLErroInf;
    private javax.swing.JLabel JLInfCad;
    private javax.swing.JLabel JLSenha1;
    private javax.swing.JPanel JPCadastre;
    private javax.swing.JPanel JPLogin;
    private javax.swing.JTextField TFCpfC;
    private javax.swing.JTextField TFEmailC;
    private javax.swing.JTextField TFLoginL;
    private javax.swing.JTextField TFSenhaC;
    private javax.swing.JTextField TFSenhaL;
    private javax.swing.JTextField TFnomeC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPMenu;
    // End of variables declaration//GEN-END:variables
}
